name: Test on Pull Request

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: chandrams/hpo
          ref: hpo_tests
          path: hpo
      - name: Build hpo
        run: |
          echo Build hpo container image
          ls
          cd hpo
          ./build_hpo.sh
          docker images | grep hpo

  test_on_native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: chandrams/hpo
          ref: hpo_tests
          path: hpo
      - name: Sanity test on native
        run: |
          echo Running sanity test on native
          ls
          cd hpo/tests
          ls
          ./test_hpo.sh -c native --resultsdir=${GITHUB_WORKSPACE} --testsuite=hpo_api_tests --testcase=hpo_sanity_test
        
      - name: Archive results
        if: always()
        run: |
          cd ${GITHUB_WORKSPACE}
          ls
          tar cvf hpo_results.tar hpo_test_results
          ls
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: hpo-results
           path: ./hpo_results.tar
           retention-days: 2

