name: Test secrets

# Controls when the action will run. 
on:
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  test_secrets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: khansaad/hpo
          path: hpo
          ref: openshift_deploy_issue
      - name: Run test
        run: |
          echo Test secrets           
          
          export REGISTRY=${{ secrets.REGISTRY }}
          export REGISTRY_USERNAME=${{ secrets.REGISTRY_USERNAME }}
          export REGISTRY_PASSWORD=${{ secrets.REGISTRY_PASSWORD }}
          export REGISTRY_EMAIL=${{ secrets.REGISTRY_EMAIL }}
          echo "Creating secret..."
          kubectl create secret docker-registry myprivaterepoaccess --docker-username=$REGISTRY_USERNAME --docker-server=$REGISTRY --docker-email=$REGISTRY_EMAIL  --docker-password=$REGISTRY_PASSWORD -n openshift-tuning
          kubectl create secret docker-registry myprivaterepoaccess --docker-username=chandra25ms --docker-server=docker.io --docker-email=chandra25.ms@gmail.com  --docker-password=$REGISTRY_PASSWORD -n openshift-tuning
          echo "Creating secret...done"
          cd hpo/tests
          ./test_hpo.sh -c minikube -o kruize/hpo:test  --testsuite=hpo_api_tests --testcase=hpo_sanity_test
         
       
        


