name: Test secrets

# Controls when the action will run. 
on:
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  # This workflow contains a single job called "deploy"
  test_secrets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
     - name: Build hpo
       run: |
         echo Test secrets
         echo "REGISTRY=${{ secrets.REGISTRY }}"
         echo "REGISTRY_USERNAME=${REGISTRY_USERNAME}"
       
         echo "REGISTRY_USERNAME=${{ secrets.REGISTRY_USERNAME }}"
       
        


