name: HPO Test secret

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY: ${{ secrets.REGISTRY }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  REGISTRY_EMAIL: ${{ secrets.REGISTRY_EMAIL }}
jobs: 
  test_on_minikube:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: khansaad/hpo
          ref: openshift_deploy_issue
          path: hpo
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
      - name: Display minikube cluster info and pods
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
     
      - name: Sanity test on minikube
        run: |
          ps -ef | grep python
          echo Running sanity test on minikube
          ls
          cd hpo/tests
          ./test_hpo.sh -c minikube -o kruize/hpo:test --resultsdir=${GITHUB_WORKSPACE} --testsuite=hpo_api_tests --testcase=hpo_sanity_test
      - name: Archive results
        if: always()
        run: |
          cd ${GITHUB_WORKSPACE}
          ls
          tar cvf hpo_minikube_results.tar hpo_test_results
          ls
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: hpo-results
           path: ./hpo_minikube_results.tar
           retention-days: 1
