name: Test Composite Action
# Controls when the action will run. 
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'design/**'
      - 'examples/**'
      - 'extensions/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
      - name: Autotune Test setup
        uses: actions/checkout@v2
        uses: actions/autotune-test-setup-composite-action@v1
          
  
      - name: Run Analyzer API tests
          run: |
            echo Running Basic API tests
            ls
            cd autotune/tests
            #./test_autotune.sh -c minikube -i autotune:int-test --tctype=functional --testsuite=basic_api_tests --resultsdir=${GITHUB_WORKSPACE} -r ${GITHUB_WORKSPACE}/benchmarks
          
